name: 'Telegram send file'
description: 'Send file to Telegram'
inputs:
  file_path:
    description: 'file_path'
    required: true
  chat_id:
    description: 'chat_id'
    required: true
  silent_mode:
    description: 'true/false'
    required: false
    default: "false"
  tg_url:
    description: 'tg_url'
    required: true

runs:
  using: "composite"
  steps:
    - name: File sending
      run: curl --max-time 1800 -Y 1000 -y 600  --limit-rate 5000 -F document=@${{ inputs.file_path }} ${{ inputs.tg_url }}/sendDocument?chat_id=${{ inputs.chat_id }}?disable_notification=${{ inputs.silent_mode }}
      shell: bash