name: 'Telegram send file'
description: 'Send file to Telegram'
inputs:
  file_path:
    description: 'file_path'
    required: true
  chat_id:
    description: 'chat_id'
    required: true
  silent_mode:
    description: 'true/false'
    required: false
    default: "false"
  tg_url:
    description: 'tg_url'
    required: true
  tg_token:
    description: 'TELEGRAM TOKEN'
    required: true
  message:
    description: 'message'
    required: true

runs:
  using: "composite"
  steps:
    - name: send file message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.chat_id }}
        token: ${{ inputs.tg_token }}
        message: ${{ inputs.message }}
        document: ${{ inputs.file_path }}

#    - name: File sending
#      run: curl -F document=@${{ inputs.file_path }} ${{ inputs.tg_url }}/sendDocument?chat_id=${{ inputs.chat_id }}?disable_notification=${{ inputs.tg_url }}
#      shell: bash