name: 'Upload crashlytics artifacts'
description: 'Upload debug info to any services'
inputs:
  app_version:
    description: 'App Version'
    required: true
  artifacts_path:
    description: 'path to downloaded artifacts'
    required: true
  firebase_app_id:
    description: 'firebase_app_id'
    required: true
  firebase_token:
    description: 'firebase_token'
    required: true
  minio_endpoint:
    description: 'minio_endpoint'
    required: true
  minio_key:
    description: 'minio_key'
    required: true
  minio_secret:
    description: 'minio_secret'
    required: true
  minio_bucked:
    description: 'minio_bucked'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload symbols to minio
      shell: bash
      env:
        MINIO_ENDPOINT: ${{ inputs.minio_endpoint }}
        MINIO_ACCESS_KEY: ${{ inputs.minio_key }}
        MINIO_SECRET_KEY: ${{ inputs.minio_secret }}
      run: |
        dir=${{ inputs.artifacts_path }}
        alias="deploy-${{ inputs.minio_bucked }}"
        mc alias set $alias $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api S3v4
        
        for file in `find $dir -d -type f -name "*.dSYM"`
        do
          mc cp $file "$alias/${{ inputs.minio_bucked }}/debug-info/${{ inputs.app_version }}/"
        done
        
        for file in `find $dir -d -type f -name "*.symbols"`
        do
          mc cp $file "$alias/${{ inputs.minio_bucked }}/debug-info/${{ inputs.app_version }}/"
        done

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: w9jds/setup-firebase@v12.9.0
      with:
        tools-version: 12.9.0
        firebase_token: ${{ inputs.firebase_token }}
    - name: Upload symbols to firebase
      shell: bash
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase_token }}
      run: |
        app_id="${{ inputs.firebase_app_id }}"
        dir=${{ inputs.artifacts_path }}

        for file in `find $dir -type f -name "*.symbols"`
        do
         echo upload $file
         firebase crashlytics:symbols:upload --app=$app_id $file
        done
  
        


