name: 'Init flutter'
description: 'Setup flutter and project dependencies'
inputs:
  flutter_version:
    description: 'flutter_version'
    required: true
runs:
  using: "composite"
  steps:
   - name: Read Flutter version
     uses: KJ002/read-yaml@1.6
     id: flutter_version
     with:
       file: './pubspec.yaml'
       key-path: '["environment","flutter"]'

   - name: Get Flutter
     uses: subosito/flutter-action@v2
     with:
       flutter-version: ${{ steps.flutter_version.outputs.data }}
       channel: 'stable'
       architecture: x64
       
   - name: Get Dependencies
     run: flutter pub get
     shell: bash