name: github_actions_flutter
repository: https://github.com/smmarty/github_actions_flutter

packages:
  - .
scripts:
  analyze:
    exec: dart analyze .
  test:
    exec: dart test .
  deps:
    exec: dart pub get
command:
  version:
    linkToCommits: false
