name: 'Check'
description: 'Check project code'
inputs:
  fatal-warnings:
    description: 'fatal-warnings'
    required: false
    default: 'true'
  fatal-infos:
    description: 'fatal-infos'
    required: false
    default: 'true'
  include_test:
    description: 'include_test [true/false]'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Analyze
      shell: bash
      run: |
        CMD_ARGS="" 
        
         if [ "${{ inputs.fatal-warnings }}" = true ]; then
           echo "Enable fatal-warnings"
           CMD_ARGS="$CMD_ARGS --fatal-warnings"
         else
          echo "Disable fatal-warnings"
          CMD_ARGS="$CMD_ARGS --no-fatal-warnings"
         fi
        
         if [ "${{ inputs.fatal-infos }}" = true ]; then
            CMD_ARGS="$CMD_ARGS --fatal-infos"
            echo "fatal-infos Enabled"
         else
           CMD_ARGS="$CMD_ARGS --no-fatal-infos"
           echo "fatal-infos disabled"
         fi
        
        flutter analyze $CMD_ARGS

    - name: Set PR Comments
      if: ${{ failure() }}
      uses: blendthink/elixir@v2

    - name: Test
      if: ${{ inputs.include_test == 'true' }}
      run: flutter test . --concurrency=16
      shell: bash
