name: 'Telegram send message with button'
description: 'Send message to Telegram'
inputs:
  message:
    description: 'message'
    required: true
  chat_id:
    description: 'chat_id'
    required: true
  silent_mode:
    description: 'true/false'
    required: false
    default: "false"
  tg_url:
    description: 'tg_url'
    required: true
  parse_mode:
    description: 'parse_mode'
    default: 'html'
    required: false
  button_link:
    description: 'Ссылка которая будет открыта по нажатию на кнопку'
    required: true
  button_text:
    description: 'Текст внутри кнопки'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send message
      shell: bash
      run: |
        text="${{ inputs.message }}"
        chat_id=${{ inputs.chat_id }}
        button_text="${{ inputs.button_text }}"
        button_link="${{ inputs.button_link }}"
        json='{"chat_id": -1, "text": "Текст сообщения", "reply_markup": {"inline_keyboard": [[{ "text": "Кнопка", "url": "https://example.com" }]]}}}'
        body="$(echo "$json" | jq  --arg chat_id $chat_id --arg text $text --arg buttonText $button_text --arg buttonLink $button_link '.chat_id = $chat_id | .text = $text | .reply_markup.inline_keyboard[0][0].text = $buttonText | .reply_markup.inline_keyboard[0][0].url = $buttonLink')"
        curl -H "Content-Type: application/json" -d $body "${{ inputs.tg_url }}/sendMessage"