name: 'Telegram send message'
description: 'Send message to Telegram'
inputs:
  message:
    description: 'message'
    required: true
  chat_id:
    description: 'chat_id'
    required: true
  silent_mode:
    description: 'true/false'
    required: false
    default: "false"
  tg_url:
    description: 'tg_url'
    required: true
  parse_mode:
    description: 'parse_mode'
    default: 'html'
    required: false

runs:
  using: "composite"
  steps:
    - name: Send message
      shell: bash
      run: |
        message=$(echo "${{ inputs.message }}" | jq --slurp --raw-input --raw-output @uri)
        curl -s -X POST "${{ inputs.tg_url }}/sendMessage" \
        -d chat_id="${{ inputs.chat_id }}" \
        -d text="$message" \
        -d disable_notification="${{ inputs.silent_mode }}" \
        -d parse_mode="${{ inputs.parse_mode }}"