name: 'Assemble Android'
description: 'Assemble apk or appbundle'
inputs:
  build_type:
    description: 'appbundle или apk'
    required: true
    default: appbundle
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release
  flavor:
    description: 'prod, dev, stage'
    required: true
    default: prod
  custom_target:
    description: 'custom build target( если не определить, то будет создан из flavor)'
    required: false
  decript_key:
    description: 'ANDROID_KEYS_SECRET_PASSPHRASE'
    required: false
  secrets_path:
    description: 'path to gpg file'
    default: 'android/keys/android_keys.zip.gpg'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Decrypt Android keys
      if: ${{ inputs.decript_key }}
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$ANDROID_KEYS_SECRET_PASSPHRASE" \
        --output android/android_keys.zip ${ANDROID_KEYS_PATH} && cd android && jar xvf android_keys.zip && cd -
      shell: bash
      env:
        ANDROID_KEYS_SECRET_PASSPHRASE: ${{ inputs.decript_key }}
        ANDROID_KEYS_PATH: ${{ inputs.secrets_path }}

    - name: Assemble
      run: |
        result_target=$BUILD_TARGET
        if [[ -z "$result_target" ]]
        then
         result_target=lib/targets/${BUILD_FLAVOR}.dart
        fi
        mode="$(tr -s "[:upper:]" "[:lower:]" <<<$BUILD_MODE)"
        echo -n "Build flavor:"$BUILD_FLAVOR"  type:"$BUILD_TYPE" target $result_target mode $mode"
        flutter build  $BUILD_TYPE -t $result_target --flavor $BUILD_FLAVOR --$mode
      shell: bash
      env:
        BUILD_FLAVOR: ${{ inputs.flavor }}
        BUILD_TARGET: ${{ inputs.custom_target }}
        BUILD_TYPE: ${{ inputs.build_type }}
        BUILD_MODE: ${{ inputs.build_mode }}