name: 'Rename file'
description: 'Assemble apk or appbundle'
inputs:
  source_file_path:
    description: 'Путь до файла'
    required: true
  file_extension:
    description: 'Расширение файла'
    required: true
  file_suffix:
    description: 'Добавит суфикс к названию файла перед расширением filename-${file_suffix}.${file_extension}'
    required: true
  file_prefix:
    description: 'Добавит префикс к названию файла перед расширением ${file_prefix}filename.${file_extension}'
    default: 'name'
    required: false

outputs:
  file-path:
    description: "New filename"
    value: ${{ steps.rename-file.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Rename output file
      id: rename-file
      shell: bash
      run: |
        SOURCE_FILE=${{ inputs.source_file_path }}
        DIR_PATH=$(dirname $SOURCE_FILE)
        TARGET_FILE_PATH=$DIR_PATH/${{ inputs.file_prefix }}-${{ inputs.source_file_name }}-${{ inputs.file_suffix}}.${{ inputs.file_extension }}
        mv -f $SOURCE_FILE $TARGET_FILE_PATH
        echo "path=$TARGET_FILE_PATH" >> $GITHUB_OUTPUT
    
