name: 'Distribute to TestFlight'
description: 'Distribute to TestFlight'
inputs:
  ipa_file_path:
    description: 'path to ipa file'
    required: false
    default: "../Runner.ipa"
  configuration:
    description: 'configuration (flavor + Build type)'
    default: 'prodRelease'
  workspace:
    description: 'xcworkspace file name (Runner.xcworkspace)'
    default: 'Runner.xcworkspace'
  scheme:
    description: 'scheme'
  app_bundle_id:
    description: 'bundle id для публикуемого приложения'
    required: true
  app_bundle_ids:
    description: 'список всех app_id через запятую (com.example.app, com.example.NotifService)'
    required: true
  app_store_connect_team_id:
    description: 'app_store_connect_team_id'
    required: true
  developer_app_id:
    description: 'developer_app_id'
    required: true
  developer_portal_team_id:
    description: 'developer_portal_team_id'
    required: true
  fastlane_apple_id:
    description: 'id от apple аккаунта'
    required: true
  fastlane_apple_application_specific_password:
    description: 'Пароль приложения от apple аккаунта(2FA)'
    required: true
  match_password:
    description: 'Пароль для расшифровки сертификатов'
    required: true
  git_authorization:
    description: 'Токен для доступа к git с сертификатами'
    required: true
  git_sercrets_url:
    description: 'url к git с сертификатами'
    required: true
  temp_keychain_user:
    description: 'Логин от временного keychain'
    required: true
  temp_keychain_password:
    description: 'Пароль от временного keychain'
    required: true
  itc_provider:
    description: 'ITC PROVIDER (TEAM ID)'
    required: true
  upload_ipa:
    description: 'Выгрузка Ipa файла в артефакты'
    default: 'false'
    required: true


runs:
  using: "composite"
  steps:
    - name: Assemble ios
      run: cd ios && fastlane distribute_to_testflight
      shell: bash
      env:
        DEVELOPER_APP_ID: ${{ inputs.developer_app_id }}
        APP_BUNDLE_ID: ${{ inputs.app_bundle_id }}
        APP_BUNDLE_IDS: ${{ inputs.app_bundle_ids }}
        TEMP_KEYCHAIN_USER: ${{ inputs.temp_keychain_user }}
        TEMP_KEYCHAIN_PASSWORD: ${{ inputs.temp_keychain_password }}
        IPA_FILE_PATH: ${{ inputs.ipa_file_path }}
        CONFIGURATION: ${{ inputs.configuration }}
        WORKSPACE: ${{ inputs.workspace }}
        SCHEME: ${{ inputs.scheme }}
        GIT_AUTHORIZATION: ${{ inputs.git_authorization }}
        ITC_PROVIDER: ${{ inputs.itc_provider }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ inputs.fastlane_apple_application_specific_password }}
        FASTLANE_USER: ${{ inputs.fastlane_apple_id }}
        MATCH_PASSWORD: ${{ inputs.match_password }}
        GIT_SECRETS_URL: ${{ inputs.git_sercrets_url }}


    - name: Upload Ipa File
      uses: actions/upload-artifact@v3
      if: ${{ inputs.upload_ipa }} && ${{ always() }}
      with:
        name: 'app_bundle_id-${{ inputs.scheme }} ipa'
        path: '**/Runner.ipa'
        retention-days: 5
