name: 'Assemble IOS'
description: 'Assemble ios ipa file'
inputs:
  flavor:
    description: 'prod, demo or dev'
    required: true
    default: dev
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release

runs:
  using: "composite"
  steps:
    - name: Assemble ios
      run: sh ./.github/scripts/assemble_ios.sh
      shell: bash
      env:
        BUILD_FLAVOR: ${{ inputs.flavor }}
        BUILD_MODE: ${{ inputs.build_mode }}