name: 'Get app version'
description: 'Return app version from pubspec'
inputs:
  file-path:
    description: "Path to your pubspec.yaml. Default is ./pubspec.yaml"
    required: false
    default: "./pubspec.yaml"
outputs:
  app-version:
    description: "Return app version"
    value: ${{ steps.pubspec.outputs.data  }}
runs:
  using: "composite"
  steps:
    - name: Read Flutter version
      uses: jbutcher5/read-yaml@main
      id: pubspec
      with:
        file: ${{ inputs.file-path }}
        key-path: '["version"]'