name: 'Telegram send message'
description: 'Send message to Telegram'
inputs:
  message:
    description: 'message'
    required: true
  chat_id:
    description: 'chat_id'
    required: true
  silent_mode:
    description: 'true/false'
    required: false
    default: "false"
  tg_url:
    description: 'tg_url'
    required: true
  parse_mode:
    description: 'parse_mode'
    default: 'MarkdownV2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Send message
      shell: bash
      run: |
        curl -X POST -H 'Content-Type: application/json' \
        -d '{"chat_id": "${{ inputs.chat_id }}", "text": "${{ inputs.message }}", "disable_notification": "${{ inputs.silent_mode }}", "parse_mode": "${{ inputs.parse_mode }}"}' \
        '${{ inputs.tg_url }}/sendMessage'