name: 'Upload file to minio storage'
description: 'Upload file to minio storage'
author: 'ns.friflex'
inputs:
  minio_endpoint:
    description: 'minio endpoint link'
    required: true
  minio_bucked:
    description: 'minio bucked alias'
    required: true
  minio_key:
    description: 'minio_key'
    required: true
  minio_secret:
    description: 'minio_secret'
    required: true
  target_path:
    description: 'Куда грузим файл?'
    required: true
  source_file:
    description: 'Путь к файлу который должен быть загружен'
    required: true
  share_filename:
    description: 'Название файла'
    required: true
outputs:
  link:
    description: 'shared link'

runs:
  using: 'composite'
  #  image: 'Dockerfile'
  steps:
    - name: 'Upload'
      shell: bash
      env:
        MINIO_ENDPOINT: ${{ inputs.minio_endpoint }}
        MINIO_ACCESS_KEY: '${{ inputs.minio_key }}'
        MINIO_SECRET_KEY: '${{ inputs.minio_secret }}'
      run: |
        mc --version
        mc alias set deploy $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api S3v4
        mc cp ${{ inputs.source_file }} "deploy/${{ inputs.minio_bucked }}/${{ inputs.share_filename }}"
        echo "link=$(mc share download "deploy/${{ inputs.minio_bucked }}/${{ inputs.share_filename }}" | grep -o 'Share: .*' | grep -o 'http.*' | jq --slurp --raw-input --raw-output @uri)" >> $GITHUB_OUTPUT

branding:
  icon: 'upload-cloud'
  color: 'red'