name: 'Upload file to minio storage'
description: 'Upload file to minio storage'
author: 'ns.friflex'
inputs:
  minio_endpoint:
    description: 'minio endpoint link'
    required: true
  minio_bucked:
    description: 'minio bucked alias'
    required: true
  minio_key:
    description: 'minio_key'
    required: true
  minio_secret:
    description: 'minio_secret'
    required: true
  target_path:
    description: 'Куда грузим файл?'
    required: true
  source_file:
    description: 'Путь к файлу который должен быть загружен'
    required: true
  share_filename:
    description: 'Название файла'
    required: true
  raw-output:
    description: 'Название файла'
    required: true
outputs:
  link:
    description: 'shared link'
    value: ${{ steps.upload.outputs.link }}
runs:
  using: 'composite'
  steps:
    - name: 'Upload'
      shell: bash
      id: upload
      env:
        MINIO_ENDPOINT: ${{ inputs.minio_endpoint }}
        MINIO_ACCESS_KEY: '${{ inputs.minio_key }}'
        MINIO_SECRET_KEY: '${{ inputs.minio_secret }}'
      run: |
        alias="deploy-${{ inputs.minio_bucked }}"
        output_path="$alias/${{ inputs.minio_bucked }}/${{ inputs.share_filename }}"
        mc alias set $alias $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api S3v4
        mc cp ${{ inputs.source_file }} $output_path
        shared_link=$(mc share download $output_path | grep -o 'Share: .*' | grep -o 'http.*')
        echo "link=$shared_link" >> $GITHUB_OUTPUT

branding:
  icon: 'upload-cloud'
  color: 'red'


