name: 'Generate changelog'
description: 'CGenerate changelog'
inputs:
  PERSONAL_ACCESS_TOKEN:
    description: 'If you use GITHUB_TOKEN instead of PERSONAL_ACCESS_TOKEN, the job wont trigger another workflow.
     Its like using [skip ci] in other CIs.'

runs:
  using: "composite"
  steps:
    - name: Check out
      if: "!startsWith(github.event.head_commit.message, 'bump:')"
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Create bump and changelog
      if: "!startsWith(github.event.head_commit.message, 'bump:')"
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ inputs.PERSONAL_ACCESS_TOKEN }}