name: 'Generate changelog'
description: 'Generate changelog'
inputs:
  github_token:
    description: 'If you use GITHUB_TOKEN instead of PERSONAL_ACCESS_TOKEN, the job wont trigger another workflow.
     Its like using [skip ci] in other CIs.'

runs:
  using: "composite"
  steps:
    - uses: bluefireteam/melos-action@v1
    - name: Generate changelog and pump version
      shell: bash
      run: melos version --all --yes  && git push