name: 'Upload crashlitycs artefact to firebase'
description: 'Upload debug info to any services'
inputs:
  app-version:
    description: 'App Version'
    required: true
  artifact-name:
    description: 'debug info'
    required: true
  firebase-token:
    description: 'firebase-token'
    required: true
  firebase-app-id:
    description: 'firebase-app-id'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Download Artifact
      id: download
      uses: actions/download-artifact@v2
#      with:
#        name: ${{ inputs.artifact-name }}
#        path: ${{ inputs.artifact-name }}

    - uses: actions/setup-node@v3
#    - uses: w9jds/setup-firebase@main
#      with:
#        tools-version: 11.9.0
#        firebase_token: ${{ inputs.firebase-token }}
    - run: |
        app_id=${{ inputs.firebase-app-id }}
        cd ${{ steps.download.outputs.download-path }}
        ls -R
#        firebase crashlytics:symbols:upload --app=\"${{ inputs.firebase-app-id }}\" \"${{ steps.download.outputs.download-path }}\"
      shell: bash

