name: 'Upload crashlitycs artefact to firebase'
description: 'Upload debug info to any services'
inputs:
  app-version:
    description: 'App Version'
    required: true
  artefact-name:
    description: 'debug info'
    required: true
  firebase-token:
    description: 'firebase-token'
    required: true
  firebase-app-id:
    description: 'firebase-app-id'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ debug-info-artefact-name }}
        path: ${{ debug-info-artefact-name }}

    - name: File sending to firebase
      uses: w9jds/firebase-action@master
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase-token }}
      with:
        args: crashlytics:symbols:upload --app=${{ inputs.firebase-app-id }} ${{ debug-info-artefact-name }}


