name: 'Upload crashlitycs artefact to firebase'
description: 'Upload debug info to any services'
inputs:
  app-version:
    description: 'App Version'
    required: true
  artifact-name:
    description: 'debug info'
    required: true
  firebase-token:
    description: 'firebase-token'
    required: true
  firebase-app-id:
    description: 'firebase-app-id'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Download Artifact
      shell: bash
      run: |
        echo ${{ inputs.artifact-name }}
        echo ${{ inputs.firebase-app-id }}
        echo ${{ inputs.app-version }}
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-name }}

    - uses: actions/setup-node@v3
    - uses: jonahsnider/firebase-action@1.0.7
      env:
        PROJECT_ID: ${{ inputs.firebase-app-id }}
        FIREBASE_TOKEN: ${{ inputs.firebase-token }}
      with:
          args: crashlytics:symbols:upload --app=${{ inputs.firebase-app-id }} ${{ inputs.artifact-name }}


