name: 'Upload debug info'
description: 'Upload debug info to any services'
inputs:
  app-version:
    description: 'App Version'
    required: true
  debug-info-path:
    description: 'debug info file path'
    required: true
  firebase-token:
    description: 'firebase-token'
    required: false
  firebase-app-id:
    description: 'firebase-app-id'
    required: false

runs:
  using: "composite"
  steps:
    - name: Upload to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debug-info app version ${{ inputs.app-version }}
        path: ${{ inputs.debug-info-path }}
        retention-days: 5

    - name: File sending to firebase
      if: ${{ inputs.firebase-token }}
      uses: w9jds/firebase-action@master
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase-token }}
      with:
        args: crashlytics:symbols:upload --app=${{ inputs.firebase-app-id }} ${{ inputs.debug-info-path }}
        
