name: 'Upload crashlytics artefact to firebase'
description: 'Upload debug info to any services'
inputs:
  app-version:
    description: 'App Version'
    required: true
  artifact-name:
    description: 'debug info'
    required: true
  firebase-token:
    description: 'firebase-token'
    required: true
  firebase-app-id:
    description: 'firebase-app-id'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Download Artifact
      id: download
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - uses: w9jds/setup-firebase@main
      with:
        tools-version: 12.3.1
        firebase_token: ${{ inputs.firebase-token }}

    - name: Upload Debug Info to Minio
      id: minio
      uses: smmarty/github_actions_flutter/actions/minio@main
      if: ${{ secrets.MINIO_BUCKET }}
      with:
        minio_endpoint: ${{ secrets.MINIO_ENDPOINT }}
        minio_bucked: ${{ secrets.MINIO_BUCKET }}
        minio_key: ${{ secrets.MINIO_KEY }}
        minio_secret: ${{ secrets.MINIO_SECRET }}
        source_file: ${{ steps.download.outputs.download-path }}
        share_filename: "debugInfo/${{ inputs.app-version }}/${{ inputs.debug-info-artifact-name }}"

    - name: Upload artifacts to firebase
      shell: bash
      run: |
        app_id=${{ inputs.firebase-app-id }}
        dir=${{ steps.download.outputs.download-path }}

        for file in `find $dir -type f -name "*.symbols"`
        do
         echo upload $file
         firebase crashlytics:symbols:upload --app=${{ inputs.firebase-app-id }} $file
        done
      env:
        FIREBASE_TOKEN: ${{ inputs.firebase-token }}
        


