name: 'Assemble Android'
description: 'Assemble apk or appbundle'
inputs:
  build_type:
    description: 'appbundle или apk'
    required: true
    default: appbundle
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release
  flavor:
    description: 'prod, dev, stage'
    required: true
    default: prod
  custom_target:
    description: 'custom build target( если не определить, то будет создан из flavor)'
    required: false
  decript_key:
    description: 'ANDROID_KEYS_SECRET_PASSPHRASE'
    required: true

runs:
  using: "composite"
  steps:
    - name: Decrypt Android keys
      if: ${{ inputs.decript_key }}
      run: sh ./.github/scripts/android/decrypt_android_keys.sh
      shell: bash
      env:
        ANDROID_KEYS_SECRET_PASSPHRASE: ${{ inputs.decript_key }}
    - name: Assemble
      run: sh ./.github/scripts/android/build_android.sh
      shell: bash
      env:
        BUILD_FLAVOR: ${{ inputs.flavor }}
        BUILD_TARGET: custom_target
        ANDROID_BUILD_TYPE: ${{ inputs.build_type }}
        BUILD_MODE: ${{ inputs.build_mode }}