name: 'Rename apk file'
description: 'Assemble apk or appbundle'
inputs:
  source_folder:
    description: 'Путь до файла не включая название и без / на конце'
    required: true
  source_file_name:
    description: 'Название файла включая расширение'
    required: true
  file_extension:
    description: 'Расширение файла'
    required: true
  file_suffix:
    description: 'Добавит суфикс к названию файла перед расширением filename-${file_suffix}.${file_extension}'
    required: true
outputs:
  file-path:
    description: "New filename"
    value: ${{ steps.rename-file.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Rename output file
      id: rename-file
      run: |
        SOURCE_FILE=${{ inputs.source_folder }}/${{ inputs.source_file_name }}.${{ inputs.file_extension }}
        FILE_NAME=${{ inputs.source_folder }}/${{ inputs.source_file_name }}-${{ inputs.file_suffix}}.${{ inputs.file_extension }}
        mv -f $SOURCE_FILE $FILE_NAME
        echo "path=$FILE_NAME" >> $GITHUB_OUTPUT
      shell: bash
