name: 'Assemble IOS'
description: 'Assemble ios ipa file'
inputs:
  flavor:
    description: 'prod, demo or dev'
    required: true
    default: dev
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release
  custom_target:
    description: 'custom build target( если не определить, то будет создан из flavor)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Assemble ios
      run: |
        result_target=${{ inputs.custom_target }} \
        if [[ -z "$result_target" ]] \
        then \
         result_target=lib/targets/${{ inputs.flavor }}.dart \
        fi \
        mode="$(tr -s "[:upper:]" "[:lower:]" <<<${{ inputs.build_mode }})" \
        echo -n "Build flavor:${{ inputs.flavor }} target $result_target mode $mode" \
        flutter build ios --flavor${{ inputs.flavor }} -t $result_target --$mode --no-codesign
      shell: bash