name: 'Assemble IOS'
description: 'Assemble ios ipa file'
inputs:
  flavor:
    description: 'prod, demo or dev'
    required: true
    default: dev
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release

runs:
  using: "composite"
  steps:
    - name: Assemble ios
      run: |
        result_target=$BUILD_TARGET
        if [[ -z "$result_target" ]]
        then
         result_target=lib/targets/${BUILD_FLAVOR}.dart
        fi

        mode="$(tr -s "[:upper:]" "[:lower:]" <<<$BUILD_MODE)"

        echo -n "Build flavor:"$BUILD_FLAVOR" target $result_target mode $mode"
        flutter build ios --flavor $BUILD_FLAVOR -t $result_target --$mode --no-codesign
      shell: bash
      env:
        BUILD_FLAVOR: ${{ inputs.flavor }}
        BUILD_MODE: ${{ inputs.build_mode }}