name: 'Assemble IOS'
description: 'Assemble ios ipa file'
inputs:
  flavor:
    description: 'prod, demo or dev'
    required: true
    default: dev
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release
  dart_define:
    description: 'Переопределяет все что будет в --dart-define=. Аргументы передаем в виде key=value,key2=value2'
    required: false
  obfuscate:
    description: 'Будет использовано --obfuscate и данные --split-debug-info будут загружены в github artifacts'
    default: 'false'
    required: false

outputs:
  debug-info-path:
    description: "Path to debug-info-folder"
    value: ${{ steps.assemble.outputs.debug_info_path }}
  debug-info-artifact-name:
    description: "debug-info-artifact-name"
    value: ${{ steps.assemble.outputs.debug-info-artifact-name }}

runs:
  using: "composite"
  steps:
    - name: Get app version
      id: app-version
      if: ${{ success() }}
      uses: smmarty/github_actions_flutter/actions/app_version@main

    - name: Assemble ios
      shell: bash
      run: |
        date=$(date +"%d-%m-%Y")
        DART_DEFINE_ARGS=" --dart-define=buildDate=$date"
        if [ ${{ inputs.obfuscate }} == true ]; then 
          mkdir debug_info
          DEBUG_DIR="debug_info"
          echo "debug_info_path=$DEBUG_DIR" >> $GITHUB_OUTPUT
          echo "debug-info-artifact-name='debug-info-${{ steps.app-version.outputs.app-version }}'" >> $GITHUB_OUTPUT
          CMD_ARGS="$CMD_ARGS --obfuscate --split-debug-info=$DEBUG_DIR"
        fi
        if [ ${{ inputs.dart_define }} != null ]; then   
         echo "Set dart_define values"
         dart_define_values="${{ inputs.dart_define }}"
         IFS=',' read -r -a dart_define_array <<< "$dart_define_values"
        for element in "${dart_define_array[@]}"
          do
           echo "dart_define add ${element}"
           DART_DEFINE_ARGS="$DART_DEFINE_ARGS --dart-define=${element}"
           done
        fi
        CMD_ARGS="$CMD_ARGS $DART_DEFINE_ARGS"
        echo $CMD_ARGS
        flutter build ios --flavor ${{ inputs.flavor }} --$(tr -s "[:upper:]" "[:lower:]" <<<${{ inputs.build_mode }}) --no-codesign $CMD_ARGS

    - name: Upload to artifacts
      uses: actions/upload-artifact@v3
      if: ${{ inputs.obfuscate }}
      with:
        name: 'debug-info-${{ steps.app-version.outputs.app-version }}'
        path: 'debug_info'
        retention-days: 5