name: 'Assemble IOS'
description: 'Assemble ios ipa file'
inputs:
  flavor:
    description: 'prod, demo or dev'
    required: true
    default: dev
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release

runs:
  using: "composite"
  steps:
    - name: Prepare build_mode
      id: mode
      run: echo $(tr -s "[:upper:]" "[:lower:]" <<<${{ inputs.build_mode }}) >> $GITHUB_OUTPUT
      shell: bash

    - name: Assemble ios
      run: flutter build ios --flavor ${{ inputs.flavor }} --${{ steps.mode.outputs.stdout }} --no-codesign
      shell: bash