name: 'Assemble IOS'
description: 'Assemble ios ipa file'
inputs:
  flavor:
    description: 'prod, demo or dev'
    required: true
    default: dev
  build_mode:
    description: 'release, profile или debug'
    required: true
    default: release
  dart_define:
    description: 'Переопределяет все что будет в --dart-define=. Аргументы передаем в виде key=value,key2=value2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Assemble ios
      shell: bash
      run: |
        date=$(date +"%d-%m-%Y")
        DART_DEFINE_ARGS=" --dart-define=buildDate=$date"
        if [ ${{ inputs.dart_define }} != null ]; then   
          echo "Set dart_define values"
          dart_define_values="${{ inputs.dart_define }}"
          IFS=',' read -r -a dart_define_array <<< "$dart_define_values"
          for element in "${dart_define_array[@]}"
          do
            echo "dart_define add ${element}"
           DART_DEFINE_ARGS="${$DART_DEFINE_ARGS} --dart-define=${element}"
          done
        fi
        CMD_ARGS="$CMD_ARGS $DART_DEFINE_ARGS"
        date=$(date +"%d-%m-%Y")
        flutter build ios --flavor ${{ inputs.flavor }} --$(tr -s "[:upper:]" "[:lower:]" <<<${{ inputs.build_mode }}) --no-codesign $CMD_ARGS
