name: 0_Analyze project code
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev, release ]

jobs:
  checkout:
    runs-on: [ self-hosted, checker ]
    steps:
      - uses: actions/checkout@v3
  setup:
      uses: smmarty/flutter_cicd_sample/.github/workflows/_setup_flutter.yaml@main
      needs: [setup]
  check:
      uses: smmarty/flutter_cicd_sample/.github/workflows/_check.yaml@main
      needs: [checkout, setup]