name: Analyze project code new
on:
  workflow_dispatch:
   inputs:
    type:
      description: 'types: [full] - include fatal-infos and fatal-warnings,[base] - exclude it'
      required: false
      default: full
    include_test:
      description: 'run tests [true/false]'
      required: false
      default: 'true'

jobs:
  analyze:
    runs-on: [ self-hosted, checker ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: smmarty/github_actions_flutter/actions/setup@main

      - name: Check
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/check@main
        with:
          type: ${{ github.event.inputs.type }}
          include_test: ${{ github.event.inputs.include_test }}
