name: 0_Analyze project code
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev, release ]

jobs:
  analyze:
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: smmarty/flutter_cicd_sample/.github/workflows/_setup_flutter.yaml@main
      - name: Check
        uses: smmarty/flutter_cicd_sample/.github/workflows/_check.yamll@main
