name: Deploy android to Telegram
on:
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'release, profile или debug'
        required: true
        default: release
        type: choice
        options:
          - release
          - profile
          - debug
      flavor:
        description: 'prod, stage, dev'
        required: true
        default: prod
        type: choice
        options:
          - prod
          - stage
          - dev
      build_type:
        description: 'apk или appbundle'
        required: true
        default: apk
        type: choice
        options:
          - apk
          - appbundle
      release_note:
        description: 'Release Note'
        required: true
        type: string
      obfuscate:
        description: 'Будет использовано --obfuscate и данные --split-debug-info будут загружены в github artifacts'
        default: false
        required: false


jobs:
  deploy_android:
    name: Deploy apk to Telegram
    uses: ./.github/workflows/_deploy_android_to_tg.yaml
    secrets: inherit
    with:
      build_type: ${{ github.event.inputs.build_type }}
      build_mode: ${{ github.event.inputs.build_mode }}
      flavor: ${{ github.event.inputs.flavor }}
      release_note: ${{ github.event.inputs.release_note }}
      obfuscate: ${{ github.event.inputs.obfuscate }}