name: Deploy apk to Telegram
on:
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'release, profile или debug'
        required: true
        default: release
        type: choice
        options:
          - release
          - profile
          - debug
      flavor:
        description: 'prod, stage, dev'
        required: true
        default: prod
        type: choice
        options:
          - prod
          - stage
          - dev
      release_note:
        description: 'Release Note'
        required: true
        type: string

jobs:
  deploy_android:
    environment: ${{ github.event.inputs.flavor }}
    name: Deploy apk to Telegram
    uses: ./.github/workflows/_deploy_apk_to_tg.yaml
    secrets: inherit
    with:
      build_mode: ${{ github.event.inputs.build_mode }}
      flavor: ${{ github.event.inputs.flavor }}
      release_note: ${{ github.event.inputs.release_note }}