name: Generate changelog
on:
  workflow_dispatch:

jobs:
  analyze:
    #    runs-on: [ self-hosted, checker ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Generate Changelog
        uses: smmarty/github_actions_flutter/actions/changelog_generator@main
