name: Analyze project code new
on:
  workflow_dispatch:

jobs:
  analyze:
    #    runs-on: [ self-hosted, checker ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Generate Changelog
        uses: smmarty/actions/changelog_generator@main
