name: Generate changelog
on:
  workflow_dispatch:
jobs:
  generate_changelog:
    #    runs-on: [ self-hosted, checker ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Generate Changelog
        uses: smmarty/github_actions_flutter/actions/changelog_generator@main
        with:
          github_token: ${{ secrets.GIT_AUTHORIZATION }}
