name: Generate changelog
on:
  workflow_dispatch:
jobs:
  generate_changelog:
    #    runs-on: [ self-hosted, checker ]
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
        fetch-depth: 0
      - name: Setup
        uses: smmarty/github_actions_flutter/actions/setup@main
      - name: Generate Changelog
        uses: smmarty/github_actions_flutter/actions/changelog_generator@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
