name: Upload to minio
on:
  workflow_dispatch:
jobs:
  minio_upload:
    # ubuntu-latest  используется только в примерах
    # Меняем на
    #    runs-on: [ self-hosted, checker ]
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload Test File
        id: minio
        uses: smmarty/github_actions_flutter/actions/minio-docker@main
        with:
          minio_endpoint: ${{ secrets.MINIO_ENDPOINT }}
          minio_bucked: ${{ secrets.MINIO_BUCKET }}
          minio_key: ${{ secrets.MINIO_KEY }}
          minio_secret: ${{ secrets.MINIO_SECRET }}
          source_file: 'CHANGELOG.md'
          share_filename: 'CHANGELOG.md'

      - name: Echo link
        if: ${{ success() }}
        run: echo "${{ steps.minio.outputs.link }}"
        shell: bash

      - name: Send release note to telegram
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/telegram/send_message_v2@main
        with:
          silent_mode: "false"
          chat_id: ${{ secrets.CHAT_ID_FOR_ANDROID_BUILDS }}
          tg_url: ${{ secrets.TG_URL }}
          parse_mode: "markdown"
          message: |
            Target: test
            Mobile services: prod
            Mobile store: gms
            Build mode: release
            BaseUrl: $(echo "https://github.com/smmarty/any?test" | jq --slurp --raw-input --raw-output @uri) 
            Obfuscated: true
            Branch: main
            Actor: ns
          
            Download link: [Link](${{ steps.minio.outputs.link }})

      - name: Artifact filepath
        id: download-file-info
        run: |
          dir=${{ steps.download.outputs.download-path }}
          file=/home/ns/services/github_runner_latest/actions-runner/_work/***_client_mobile/***_client_mobile/artifacts/android-build-artifact/app-prod-gms-release.apk
          echo "file-info=$file" >> $GITHUB_OUTPUT    

      - name: ECHO RESULT
        run: echo ${{ steps.download-file-info.outputs.file-info }}
