name: Deploy android to Telegram
on:
  workflow_dispatch:
    inputs:
      release_note:
        description: 'Release Note'
        required: true
        type: string


jobs:
  deploy_android:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Send test message
      uses: smmarty/github_actions_flutter/actions/telegram/send_message@main
      with:
        silent_mode: "false"
        chat_id: ${{ secrets.ALERTS_CHAT_ID }}
        tg_url: ${{ secrets.TG_URL }}
        message: ${{ inputs.release_note }}