name: 1_Analyze project code
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev, release ]

jobs:
  analyze:
    runs-on: [ self-hosted, checker ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./ci/actions/setup-action.yml
      - name: Check
        uses: ./ci/actions/check-action.yml