name: _deploy android to Telegram
on:
  workflow_call:
    inputs:
      build_mode:
        description: 'release, profile или debug'
        required: true
        default: release
        type: string
      flavor:
        description: 'prod, stage, dev'
        required: false
        type: string
      release_note:
        description: 'Release Note'
        required: true
        type: string
      build_type:
        description: 'apk или appbundle'
        type: string
        required: true
        default: apk
      obfuscate:
        description: 'Будет использовано --obfuscate и данные --split-debug-info будут загружены в github artifacts'
        type: string
        default: false
        required: false
jobs:
  deploy_android:
    # ubuntu-latest  используется только в примерах
    # Меняем на
    #    runs-on: [ self-hosted, android_builder  ]
    runs-on: [ ubuntu-latest ]
    environment: ${{ inputs.flavor }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: smmarty/github_actions_flutter/actions/setup@main

      - name: Check
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/check@main

      - name: Assemble
        id: assemble
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/assemble_android_v2@main
        with:
          build_type: ${{ inputs.build_type }}
          build_mode: ${{ inputs.build_mode }}
          flavor: ${{ inputs.flavor }}
          obfuscate: ${{ inputs.obfuscate }}

      - name: Send file to telegram
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/telegram/send_file@main
        with:
          silent_mode: "true"
          file_path: ${{ steps.assemble.outputs.build-file }}
          chat_id: ${{ secrets.CHAT_ID_FOR_ANDROID_BUILDS }}
          tg_url: ${{ secrets.TG_URL }}

      - name: Send release note to telegram
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/telegram/send_message@main
        with:
          message: |
            New android build
            Type: ${{ steps.assemble.outputs.ext }}
            Branch: ${{ github.ref_name }}
            Actor: ${{ github.actor }} 
            Version: ${{ steps.assemble.outputs.app-version }} 
            File Name: $(basename ${{ steps.assemble.outputs.build-file}})
            Release Note: 
             ${{ inputs.release_note }}
          silent_mode: "false"
          chat_id: ${{ secrets.CHAT_ID_FOR_ANDROID_BUILDS }}
          tg_url: ${{ secrets.TG_URL }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ inputs.obfuscate }}
        with:
          name: Debug Info ${{ steps.assemble.outputs.app-version }}
          path: ${{ steps.assemble.outputs.debug-info-path }}

      - name: Send alert
        if: ${{ failure() }}
        uses: smmarty/github_actions_flutter/actions/telegram/send_message@main
        with:
          silent_mode: "false"
          chat_id: ${{ secrets.ALERTS_CHAT_ID }}
          tg_url: ${{ secrets.TG_URL }}
          message: |
            Action: ${{ github.workflow }}
            Repository: ${{ github.repository }}
            Actor: ${{ github.actor }} 
            Job: ${{ github.job }}
            Branch: ${{ github.ref }}
            Status:  Failure
            Link: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}

