name: _deploy appbundle to Telegram
on:
  workflow_call:
    inputs:
      build_mode:
        description: 'release, profile или debug'
        required: true
        default: release
        type: string
      flavor:
        description: 'prod, stage, dev'
        required: true
        default: prod
        type: string
      release_note:
        description: 'Release Note'
        required: true
        type: string

jobs:
  deploy_appbundle:
    # ubuntu-latest  используется только в примерах
    # Меняем на
    #    runs-on: [ self-hosted, android_builder  ]
    runs-on: [ ubuntu-latest ]
    environment: ${{ github.event.inputs.flavor }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: smmarty/github_actions_flutter/actions/setup@main

      - name: Check
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/check@main

      - name: Assemble
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/assemble_android@main
        with:
          build_type: appbundle
          build_mode: ${{ github.event.inputs.build_mode }}
          flavor: ${{ github.event.inputs.flavor }}
          decript_key: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
          secrets_path: 'android/keys/android_keys.zip.gpg'

      - name: Get app version
        id: app-version
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/app_version@main

      - name: Rename bundle file
        id: file-path
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/rename_file@main
        with:
          source_folder: build/app/outputs/*/*/
          source_file_name: app-${{ github.event.inputs.flavor }}-${{ github.event.inputs.build_mode }}
          file_extension: aab
          file_suffix: ${{ steps.app-version.outputs.app-version }}
          file_prefix: PREFIX

      - name: Send appbundle file to telegram
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/telegram/send_file@main
        with:
          silent_mode: "true"
          file_path: ${{ steps.file-path.outputs.file-path}}
          chat_id: ${{ secrets.CHAT_ID_FOR_ANDROID_BUILDS }}
          tg_url: ${{ secrets.TG_URL }}

      - name: Send release note to telegram
        if: ${{ success() }}
        uses: smmarty/github_actions_flutter/actions/telegram/send_message@main
        with:
          message: |
            New android build: 
            Type: appbundle
            Branch: ${{ github.ref_name }}
            Actor: ${{ github.actor }} 
            Version: ${{ steps.app-version.outputs.app-version }} 
            Release Note: 
              ${{ github.event.inputs.release_note }}
          silent_mode: "false"
          chat_id: ${{ secrets.CHAT_ID_FOR_ANDROID_BUILDS }}
          tg_url: ${{ secrets.TG_URL }}

      - name: Send alert
        if: ${{ failure() }}
        uses: smmarty/github_actions_flutter/actions/telegram/send_message@main
        with:
          silent_mode: "false"
          chat_id: ${{ secrets.ALERTS_CHAT_ID }}
          tg_url: ${{ secrets.TG_URL }}
          message: |
            Action: ${{ github.workflow }}
            Repository: ${{ github.repository }}
            Actor: ${{ github.actor }} 
            Branch: ${{ github.ref }}
            Status:  Failure
            Link: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}