name: _on Pull Request Analyze project code
on:
  pull_request:
    branches: [ main, dev, release ]

jobs:
  analyze:
    runs-on: [ self-hosted, checker, test ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        if: ${{ success() }}
        uses: ./.github/actions/check