name: _on Pull Request Analyze project code
on:
  pull_request:
    branches: [ main, dev, release ]

jobs:
  analyze:
#    runs-on: [ self-hosted, checker, test ]
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses:  smmarty/github_actions_flutter/actions/setup@main

      - name: Check
        if: ${{ success() }}
        uses:  smmarty/github_actions_flutter/actions/check@main