on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review, synchronize]
jobs:
  labeler:
#    runs-on: [self-hosted,tag_manager]
    runs-on: [ ubuntu-latest ]
    name: Label the PR size
    steps:
      - uses: actions/checkout@v3
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          dry-run: false
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          android_label: 'android'
          ios: 'ios'
          web: 'web'
          main_changed: 'main_changed'
          xs_label: 'XS'
          xs_max_size: '10'
          s_label: 'S'
          s_max_size: '100'
          m_label: 'M'
          m_max_size: '500'
          l_label: 'L'
          l_max_size: '1000'
          xl_label: 'XL'
          fail_if_xl: 'false'
#          message_if_xl: >
#            This PR exceeds the recommended size of 1000 lines.
#            Please make sure you are NOT addressing multiple issues with one PR.
#            Note this PR might be rejected due to its size.
          files_to_ignore: '*.g.dart *.freezed.dart *.config.dart lib/l10n/app_ru.arb *.gen.dart pubspec.lock'
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
