name: Assemble ios and distribute to TestFlight
on:
  workflow_dispatch:
   inputs:
     build_mode:
       description: 'release, profile или debug'
       required: true
       default: release
       type: choice
       options:
         - release
         - profile
         - debug
     flavor:
       description: 'prod,stage,dev'
       required: true
       default: prod
       type: choice
       options:
         - prod
         - stage
         - dev
jobs:
  assemble_ios:
    runs-on: [ self-hosted, ios_builder, test ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Check
        if: ${{ success() }}
        uses: ./.github/actions/check
      - name: Assemble
        if: ${{ success() }}
        uses: ./.github/actions/assemble_ios
        with:
          build_mode: ${{ github.event.inputs.build_mode }}
          flavor: ${{ github.event.inputs.flavor }}