name: Test_alert
on:
  workflow_dispatch:

jobs:
  deploy_android:
    runs-on: [ self-hosted, android_builder ]
    steps:
      - uses: actions/checkout@v3
      - name: Send alert
        uses: ./.github/actions/telegram/send_message
        with:
          silent_mode: "false"
          chat_id: ${{ secrets.ALERTS_CHAT_ID }}
          tg_url: ${{ secrets.TG_URL }}
          message: |
            Action ${{ github.workflow }}
            Repository ${{ github.repository }}
            Branch ${{ github.ref }}
            Status  Failure
            Link ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}