name: 'Generate env'
description: 'Запускает build runner и проверяет env через friflex_env'
inputs:
  secret_path:
    required: true
    description: 'Путь до файла с секретами'
  env_path:
    required: true
    description: 'Путь до env файла'
  password:
    required: true
    description: 'Пароль от файла с секретами'

runs:
  using: "composite"
  steps:
    - name: Extract env
      shell: bash
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="${{ inputs.password }}" \
        --output ${{ inputs.secret_path }} ${{ inputs.env_path }}

    - name: Run build runner
      shell: bash
      run: |
        flutter packages pub run build_runner build --delete-conflicting-outputs

    - name: Test
      shell: bash
      run: |
        flutter test test/config/evn_test.dart  
        
